### ISSUE TITLE
Is this still supported?

### ISSUE THREAD

**Issue by jpruiz114** [wesbos/HTML5-Security-Camera#3]
Hi. I'm trying to execute this but it just stays loading for ever.

**Comment by wesbos** [comment]
Hey - I haven't touched this in years so I'm not sure it still works. Would be fun to take a look at again though...

**Comment by wesbos** [comment]
Cool - it was really easy to update it for the latest node! 

Check the main repo now

**Comment by jpruiz114** [comment]
Gonna check and leave my thoughts. Thanks for taking a look at it.

**Comment by wesbos** [comment]
Cool - it's pretty gnarly code - I wrote it 4 years back. But it works :)
